name: testing branch synchronization 
on:
  push:
    branches: [test]
  pull_request:
    branches: [main]  
jobs:
  build:
    env:
      sourceBranch: ${{ github.event.pull_request.SourceBranch }}
    #if($sourceBranch -ne "test")
      #{
        #exit 1
      #}
    runs-on: ubuntu-latest
    steps:
    - name: test sync
      run: |
        echo "merged branch: $sourceBranch"
