name: testing branch synchronization 
on:
  push:
    branches: [main]
  pull_request:
    branches: [test]  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test sync
      run: |
          echo "hello babu"
